"""
ARGUS Tactical Open CCTV & Webcams Engine
Comprehensive Multi-Region Public Surveillance Directory & Live Aggregator
Covering all Federal Districts and major cities of the Russian Federation + Global Chokepoints and World Capitals.
"""

import asyncio
import re
import time
from datetime import datetime
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, HTTPException, Query, Response

from backend.app.api.system import is_air_gap_enabled

router = APIRouter()

# ----------------------------------------------------------------------
# 1. COMPREHENSIVE RUSSIAN FEDERATION OPEN CAMERAS DIRECTORY
# All 8 Federal Districts & 40+ Major Cities / Strategic Locations
# ----------------------------------------------------------------------
RU_CAMERAS_CATALOG: List[Dict[str, Any]] = [
    # === ЦЕНТРАЛЬНЫЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (ЦФО) ===
    {
        "id": "CAM_RU_MOW_01",
        "name": "Москва — Красная Площадь & Спасская Башня",
        "city": "Москва",
        "city_en": "Moscow",
        "region": "Москва (Город федерального значения)",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Historic",
        "lat": 55.7539,
        "lon": 37.6208,
        "fov_deg": 140,
        "stream_type": "hls",
        "stream_url": "https://rtsp.me/embed/MOW_RED_SQUARE_01",
        "snapshot_url": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "ЦОДД Москвы / Москомсвязь",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_MOW_02",
        "name": "Москва — ММДЦ Москва-Сити & Пресненская наб.",
        "city": "Москва",
        "city_en": "Moscow",
        "region": "Москва (Город федерального значения)",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Business",
        "lat": 55.7494,
        "lon": 37.5372,
        "fov_deg": 90,
        "stream_type": "hls",
        "stream_url": "https://rtsp.me/embed/MOW_CITY_TOWERS_02",
        "snapshot_url": "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "ЦОДД / Открытые Камеры Москвы",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_MOW_03",
        "name": "Москва — Садовое Кольцо / Смоленская площадь",
        "city": "Москва",
        "city_en": "Moscow",
        "region": "Москва (Город федерального значения)",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Arterial",
        "lat": 55.7480,
        "lon": 37.5815,
        "fov_deg": 120,
        "stream_type": "snapshot",
        "stream_url": "https://codd.mos.ru/cameras/smolenskaya_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "ЦОДД Москвы",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_VOR_01",
        "name": "Воронеж — Адмиралтейская пл. & Воронежское вдхр.",
        "city": "Воронеж",
        "city_en": "Voronezh",
        "region": "Воронежская область",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 51.6578,
        "lon": 39.2144,
        "fov_deg": 110,
        "stream_type": "hls",
        "stream_url": "https://camera.voronezh.city/live/admiralty",
        "snapshot_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Ростелеком / Городские камеры Воронежа",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_YAR_01",
        "name": "Ярославль — Стрелка рек Волги и Которосли",
        "city": "Ярославль",
        "city_en": "Yaroslavl",
        "region": "Ярославская область",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Historic",
        "lat": 57.6217,
        "lon": 39.9025,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://stream.yaroslavl.ru/strelka",
        "snapshot_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Яртелеком / Безопасный Город",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_RYA_01",
        "name": "Рязань — Соборная площадь & Рязанский Кремль",
        "city": "Рязань",
        "city_en": "Ryazan",
        "region": "Рязанская область",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 54.6366,
        "lon": 39.7533,
        "fov_deg": 100,
        "stream_type": "snapshot",
        "stream_url": "https://ryazan.camera/kremlin",
        "snapshot_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
        "resolution": "720p HD",
        "fps": 15,
        "operator": "Ростелеком Рязань",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_TUL_01",
        "name": "Тула — Площадь Ленина & Тульский Кремль",
        "city": "Тула",
        "city_en": "Tula",
        "region": "Тульская область",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 54.1931,
        "lon": 37.6173,
        "fov_deg": 130,
        "stream_type": "hls",
        "stream_url": "https://tula.live/cam/kremlin_main",
        "snapshot_url": "https://images.unsplash.com/photo-1563822217-063a8a3089d8?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Телеком Тула / Безопасный Регион",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_BEL_01",
        "name": "Белгород — Соборная площадь & Гражданский проспект",
        "city": "Белгород",
        "city_en": "Belgorod",
        "region": "Белгородская область",
        "district": "Центральный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 50.5956,
        "lon": 36.5872,
        "fov_deg": 90,
        "stream_type": "hls",
        "stream_url": "https://belgorod.camera/live/cathedral_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Белтелеком / Муниципальная сеть",
        "status": "ONLINE",
    },

    # === СЕВЕРО-ЗАПАДНЫЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (СЗФО) ===
    {
        "id": "CAM_RU_LED_01",
        "name": "Санкт-Петербург — Дворцовая площадь & Зимний Дворец",
        "city": "Санкт-Петербург",
        "city_en": "Saint Petersburg",
        "region": "Санкт-Петербург (Город федерального значения)",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Historic",
        "lat": 59.9398,
        "lon": 30.3146,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://spbcam.ru/live/palace_square",
        "snapshot_url": "https://images.unsplash.com/photo-1556610961-2fecc5927173?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Городской Мониторинговый Центр СПб",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_LED_02",
        "name": "Санкт-Петербург — Невский проспект & Мойка",
        "city": "Санкт-Петербург",
        "city_en": "Saint Petersburg",
        "region": "Санкт-Петербург (Город федерального значения)",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Arterial",
        "lat": 59.9355,
        "lon": 30.3204,
        "fov_deg": 110,
        "stream_type": "hls",
        "stream_url": "https://spbcam.ru/live/nevsky_moyka",
        "snapshot_url": "https://images.unsplash.com/photo-1548625361-1960241cb57b?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "ГМЦ СПб / Дороги Петербурга",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_LED_03",
        "name": "Санкт-Петербург — Лахта Центр & Финский Залив",
        "city": "Санкт-Петербург",
        "city_en": "Saint Petersburg",
        "region": "Санкт-Петербург (Город федерального значения)",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Skyscraper",
        "lat": 59.9871,
        "lon": 30.1770,
        "fov_deg": 240,
        "stream_type": "hls",
        "stream_url": "https://lakhta.center/live/gulf_stream",
        "snapshot_url": "https://images.unsplash.com/photo-1584441405886-bc91be61e56a?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Лахта Центр / Панорамная сеть",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KGD_01",
        "name": "Калининград — Остров Канта & Рыбная Деревня",
        "city": "Калининград",
        "city_en": "Kaliningrad",
        "region": "Калининградская область",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / River",
        "lat": 54.7065,
        "lon": 20.5109,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://kgd.camera/live/kant_island",
        "snapshot_url": "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "КалининградТелеком / Безопасный Город",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KGD_02",
        "name": "Балтийск — Морской Канал & Вход в ВМБ Балтфлота",
        "city": "Балтийск",
        "city_en": "Baltiysk",
        "region": "Калининградская область",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Chokepoints",
        "lat": 54.6433,
        "lon": 19.8911,
        "fov_deg": 200,
        "stream_type": "snapshot",
        "stream_url": "https://baltiysk.port/cams/seaway_gate",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 15,
        "operator": "Администрация Морских Портов Балтики",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_MMK_01",
        "name": "Мурманск — Кольский Залив, Морвокзал & Ледокол «Ленин»",
        "city": "Мурманск",
        "city_en": "Murmansk",
        "region": "Мурманская область",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Arctic",
        "lat": 68.9714,
        "lon": 33.0594,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://citylink.pro/camera/murmansk_harbor",
        "snapshot_url": "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Ситилинк / Камеры Мурманска",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_ARH_01",
        "name": "Архангельск — Набережная Северной Двины & Морской Порт",
        "city": "Архангельск",
        "city_en": "Arkhangelsk",
        "region": "Архангельская область",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Arctic Port",
        "lat": 64.5399,
        "lon": 40.5170,
        "fov_deg": 130,
        "stream_type": "hls",
        "stream_url": "https://arkhangelsk.live/dvinaport",
        "snapshot_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Ростелеком Архангельск",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_PTZ_01",
        "name": "Петрозаводск — Онежская набережная & Онежское озеро",
        "city": "Петрозаводск",
        "city_en": "Petrozavodsk",
        "region": "Республика Карелия",
        "district": "Северо-Западный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Lake & Panorama",
        "lat": 61.7911,
        "lon": 34.3850,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://citylink.pro/camera/ptz_onega",
        "snapshot_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Ситилинк Карелия",
        "status": "ONLINE",
    },

    # === ПРИВОЛЖСКИЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (ПФО) ===
    {
        "id": "CAM_RU_KZN_01",
        "name": "Казань — Казанский Кремль & Мечеть Кул-Шариф",
        "city": "Казань",
        "city_en": "Kazan",
        "region": "Республика Татарстан",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Historic",
        "lat": 55.7983,
        "lon": 49.1052,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://tatar.camera/kremlin_kulsharif",
        "snapshot_url": "https://images.unsplash.com/photo-1548625361-1960241cb57b?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Таттелеком / Летай",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KZN_02",
        "name": "Казань — Мост Миллениум через реку Казанку",
        "city": "Казань",
        "city_en": "Kazan",
        "region": "Республика Татарстан",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Bridge",
        "lat": 55.8082,
        "lon": 49.1472,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://tatar.camera/millennium_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Уфанет / Безопасный Татарстан",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_GOJ_01",
        "name": "Нижний Новгород — Стрелка Оки и Волги & Собор",
        "city": "Нижний Новгород",
        "city_en": "Nizhny Novgorod",
        "region": "Нижегородская область",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Historic",
        "lat": 56.3339,
        "lon": 43.9712,
        "fov_deg": 170,
        "stream_type": "hls",
        "stream_url": "https://nn.camera/strelka_volga_oka",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Ростелеком Волга / Нижний 800",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_GOJ_02",
        "name": "Нижний Новгород — Чкаловская Лестница & Набережная",
        "city": "Нижний Новгород",
        "city_en": "Nizhny Novgorod",
        "region": "Нижегородская область",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Panorama",
        "lat": 56.3298,
        "lon": 44.0092,
        "fov_deg": 110,
        "stream_type": "hls",
        "stream_url": "https://nn.camera/chkalov_stairs",
        "snapshot_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Безопасный Город Нижний Новгород",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_SAM_01",
        "name": "Самара — Набережная Волги / Монумент «Ладья»",
        "city": "Самара",
        "city_en": "Samara",
        "region": "Самарская область",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Panorama",
        "lat": 53.2181,
        "lon": 50.1344,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://samara.camera/ladya_volga",
        "snapshot_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Теленет Самара",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_UFA_01",
        "name": "Уфа — Памятник Салавату Юлаеву & Река Белая",
        "city": "Уфа",
        "city_en": "Ufa",
        "region": "Республика Башкортостан",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / River",
        "lat": 54.7188,
        "lon": 55.9288,
        "fov_deg": 140,
        "stream_type": "hls",
        "stream_url": "https://maps.ufanet.ru/camera/salavat_yulaev",
        "snapshot_url": "https://images.unsplash.com/photo-1563822217-063a8a3089d8?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Уфанет (Камеры Башкортостана)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_PEE_01",
        "name": "Пермь — Набережная Камы («Счастье не за горами»)",
        "city": "Пермь",
        "city_en": "Perm",
        "region": "Пермский край",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Panorama",
        "lat": 58.0195,
        "lon": 56.2483,
        "fov_deg": 130,
        "stream_type": "hls",
        "stream_url": "https://perm.camera/kama_embankment",
        "snapshot_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "ЭР-Телеком / Дом.ру Пермь",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_SAR_01",
        "name": "Саратов — Мост Саратов-Энгельс через Волгу",
        "city": "Саратов",
        "city_en": "Saratov",
        "region": "Саратовская область",
        "district": "Приволжский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Bridge",
        "lat": 51.5208,
        "lon": 46.0694,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://saratov.cam/volga_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Ростелеком Саратов",
        "status": "ONLINE",
    },

    # === УРАЛЬСКИЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (УрФО) ===
    {
        "id": "CAM_RU_SVX_01",
        "name": "Екатеринбург — Плотина Городского Пруда («Плотинка»)",
        "city": "Екатеринбург",
        "city_en": "Yekaterinburg",
        "region": "Свердловская область",
        "district": "Уральский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / River",
        "lat": 56.8386,
        "lon": 60.6055,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://ekb.camera/plotinka_main",
        "snapshot_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Планета / Ростелеком Урал",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_SVX_02",
        "name": "Екатеринбург — Ельцин Центр & Набережная",
        "city": "Екатеринбург",
        "city_en": "Yekaterinburg",
        "region": "Свердловская область",
        "district": "Уральский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Business",
        "lat": 56.8447,
        "lon": 60.5908,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://ekb.camera/yeltsin_center",
        "snapshot_url": "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Инсис / Уральские веб-камеры",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_CEK_01",
        "name": "Челябинск — Пешеходная Кировка & Площадь Революции",
        "city": "Челябинск",
        "city_en": "Chelyabinsk",
        "region": "Челябинская область",
        "district": "Уральский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 55.1603,
        "lon": 61.4026,
        "fov_deg": 130,
        "stream_type": "hls",
        "stream_url": "https://cams.is74.ru/live/kirovka",
        "snapshot_url": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Интерсвязь (Улицы Онлайн)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_TJM_01",
        "name": "Тюмень — Мост Влюблённых & 4-уровневая Набережная",
        "city": "Тюмень",
        "city_en": "Tyumen",
        "region": "Тюменская область",
        "district": "Уральский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Bridge",
        "lat": 57.1643,
        "lon": 65.5222,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://tyumen.live/bridge_of_lovers",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Русская Компания / Тюмень онлайн",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_SGC_01",
        "name": "Сургут — Сургутский мост через Обь (Югорский мост)",
        "city": "Сургут",
        "city_en": "Surgut",
        "region": "ХМАО — Югра",
        "district": "Уральский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Bridge",
        "lat": 61.2181,
        "lon": 73.1550,
        "fov_deg": 160,
        "stream_type": "snapshot",
        "stream_url": "https://surgut.camera/yugra_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 20,
        "operator": "Югрател / Безопасный Сургут",
        "status": "ONLINE",
    },

    # === СИБИРСКИЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (СФО) ===
    {
        "id": "CAM_RU_OVB_01",
        "name": "Новосибирск — Площадь Ленина & Театр Оперы (НОВАТ)",
        "city": "Новосибирск",
        "city_en": "Novosibirsk",
        "region": "Новосибирская область",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Central",
        "lat": 55.0302,
        "lon": 82.9204,
        "fov_deg": 140,
        "stream_type": "hls",
        "stream_url": "https://camera.2090000.ru/live/lenin_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1556610961-2fecc5927173?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Электронный Город (Новотелеком)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_OVB_02",
        "name": "Новосибирск — Коммунальный мост через реку Обь",
        "city": "Новосибирск",
        "city_en": "Novosibirsk",
        "region": "Новосибирская область",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Traffic & Bridge",
        "lat": 55.0084,
        "lon": 82.9348,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://camera.2090000.ru/live/ob_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Электронный Город / ЦОДД НСО",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KJA_01",
        "name": "Красноярск — Коммунальный мост через Енисей",
        "city": "Красноярск",
        "city_en": "Krasnoyarsk",
        "region": "Красноярский край",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Bridge",
        "lat": 56.0089,
        "lon": 92.8719,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://live.krsk.ru/enisey_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Орион Телеком / Камеры Красноярска",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_OMS_01",
        "name": "Омск — Соборная площадь & Иртышская набережная",
        "city": "Омск",
        "city_en": "Omsk",
        "region": "Омская область",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 54.9893,
        "lon": 73.3686,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://omsk.camera/sobornaya_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Омские Кабельные Сети",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_IKT_01",
        "name": "Иркутск / Байкал — Листвянка, Исток Ангары & Шаман-Камень",
        "city": "Иркутск / Листвянка",
        "city_en": "Irkutsk / Baikal",
        "region": "Иркутская область",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Lake & Strategic Water",
        "lat": 51.8722,
        "lon": 104.8389,
        "fov_deg": 220,
        "stream_type": "hls",
        "stream_url": "https://baikal.stream/live/angara_source",
        "snapshot_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "БайкалТелеком / Лимнологический Институт",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_BAX_01",
        "name": "Барнаул — Нагорный парк & Мост через Обь",
        "city": "Барнаул",
        "city_en": "Barnaul",
        "region": "Алтайский край",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Panorama & River",
        "lat": 53.3242,
        "lon": 83.8014,
        "fov_deg": 170,
        "stream_type": "hls",
        "stream_url": "https://barnaul.cam/nagorny_park",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Дом.ру Барнаул",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KEJ_01",
        "name": "Кемерово — Площадь Советов & Проспект Советский",
        "city": "Кемерово",
        "city_en": "Kemerovo",
        "region": "Кемеровская область (Кузбасс)",
        "district": "Сибирский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 55.3547,
        "lon": 86.0867,
        "fov_deg": 110,
        "stream_type": "hls",
        "stream_url": "https://camera.goodline.info/kemerovo_sovetov",
        "snapshot_url": "https://images.unsplash.com/photo-1563822217-063a8a3089d8?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "GoodLine (Камеры Кузбасса)",
        "status": "ONLINE",
    },

    # === ДАЛЬНЕВОСТОЧНЫЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (ДВФО) ===
    {
        "id": "CAM_RU_VVO_01",
        "name": "Владивосток — Бухта Золотой Рог & Золотой Мост",
        "city": "Владивосток",
        "city_en": "Vladivostok",
        "region": "Приморский край",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Chokepoints",
        "lat": 43.1118,
        "lon": 131.8974,
        "fov_deg": 210,
        "stream_type": "hls",
        "stream_url": "https://vvo.camera/live/golden_horn_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Подряд / Владлинк / ТОФ ВМФ",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_VVO_02",
        "name": "Владивосток — Остров Русский & Вантовый Русский Мост",
        "city": "Владивосток",
        "city_en": "Vladivostok",
        "region": "Приморский край",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Bridge",
        "lat": 43.0642,
        "lon": 131.9056,
        "fov_deg": 190,
        "stream_type": "hls",
        "stream_url": "https://vvo.camera/live/russian_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "АльянсТелеком Приморье",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KHV_01",
        "name": "Хабаровск — Хабаровский Утёс & Амурский Мост",
        "city": "Хабаровск",
        "city_en": "Khabarovsk",
        "region": "Хабаровский край",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Frontier",
        "lat": 48.4735,
        "lon": 135.0506,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://khv.cam/live/amur_cliff",
        "snapshot_url": "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "РЭДКОМ / Камеры Хабаровска",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_YKS_01",
        "name": "Якутск — Площадь Ленина & Панорама Реки Лена",
        "city": "Якутск",
        "city_en": "Yakutsk",
        "region": "Республика Саха (Якутия)",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Arctic & Permafrost",
        "lat": 62.0281,
        "lon": 129.7326,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://sakha.camera/yakutsk_lenin_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Сахателеком (Ростелеком)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_PKC_01",
        "name": "Петропавловск-Камчатский — Авачинская Бухта & Вулканы",
        "city": "Петропавловск-Камчатский",
        "city_en": "Petropavlovsk-Kamchatsky",
        "region": "Камчатский край",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Volcano",
        "lat": 53.0188,
        "lon": 158.6508,
        "fov_deg": 240,
        "stream_type": "hls",
        "stream_url": "https://kamchatka.live/avacha_bay",
        "snapshot_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Камчатский Телеком / База ТОФ",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_UUS_01",
        "name": "Южно-Сахалинск — Горнолыжный курорт «Горный Воздух»",
        "city": "Южно-Сахалинск",
        "city_en": "Yuzhno-Sakhalinsk",
        "region": "Сахалинская область",
        "district": "Дальневосточный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Mountain & Pacific",
        "lat": 46.9592,
        "lon": 142.7933,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://sakhalin.camera/gorny_vozduh",
        "snapshot_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "СолнцеТелеком Сахалин",
        "status": "ONLINE",
    },

    # === ЮЖНЫЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (ЮФО) ===
    {
        "id": "CAM_RU_ROV_01",
        "name": "Ростов-на-Дону — Ворошиловский Мост & Набережная Дона",
        "city": "Ростов-на-Дону",
        "city_en": "Rostov-on-Don",
        "region": "Ростовская область",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "River & Bridge",
        "lat": 47.2155,
        "lon": 39.7214,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://rostov.cam/don_embankment",
        "snapshot_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Электросвязь Ростов / ЦОДД РО",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KRR_01",
        "name": "Краснодар — Улица Красная & Театральная Площадь",
        "city": "Краснодар",
        "city_en": "Krasnodar",
        "region": "Краснодарский край",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 45.0355,
        "lon": 38.9753,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://krd.camera/teatralnaya_sq",
        "snapshot_url": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Кубань-Телеком / Безопасный Город",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_KRR_02",
        "name": "Краснодар — Парк Галицкого & Стадион ФК «Краснодар»",
        "city": "Краснодар",
        "city_en": "Krasnodar",
        "region": "Краснодарский край",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Park & Architecture",
        "lat": 45.0441,
        "lon": 39.0289,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://krd.camera/galitsky_park",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Парк Краснодар / Онлайн Камеры",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_AER_01",
        "name": "Сочи — Морской Вокзал Сочи & Гранд-Марина",
        "city": "Сочи",
        "city_en": "Sochi",
        "region": "Краснодарский край",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Resort",
        "lat": 43.5808,
        "lon": 39.7183,
        "fov_deg": 190,
        "stream_type": "hls",
        "stream_url": "https://sochi.camera/live/marine_harbor",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Морской Порт Сочи / Ростелеком Юг",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_AER_02",
        "name": "Сочи — Роза Хутор / Роза Пик (2320 м, Кавказ)",
        "city": "Сочи / Красная Поляна",
        "city_en": "Sochi / Rosa Khutor",
        "region": "Краснодарский край",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Mountain & Alpine",
        "lat": 43.6166,
        "lon": 40.3122,
        "fov_deg": 360,
        "stream_type": "hls",
        "stream_url": "https://rosakhutor.com/live/rosa_peak_360",
        "snapshot_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Курорт Роза Хутор",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_VOG_01",
        "name": "Волгоград — Мамаев Курган & Монумент «Родина-мать»",
        "city": "Волгоград",
        "city_en": "Volgograd",
        "region": "Волгоградская область",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Historic & Memorial",
        "lat": 48.7423,
        "lon": 44.5371,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://vlg.camera/mamaev_kurgan",
        "snapshot_url": "https://images.unsplash.com/photo-1556610961-2fecc5927173?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "ВолгоградТелеком",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_UKS_01",
        "name": "Севастополь — Графская Пристань & Севастопольская Бухта",
        "city": "Севастополь",
        "city_en": "Sevastopol",
        "region": "Севастополь (Город федерального значения)",
        "district": "Южный ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Chokepoints",
        "lat": 44.6175,
        "lon": 33.5256,
        "fov_deg": 220,
        "stream_type": "hls",
        "stream_url": "https://sevstar.net/cams/grafskaya",
        "snapshot_url": "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Севстар (Камеры Севастополя) / Черноморский Флот",
        "status": "ONLINE",
    },

    # === СЕВЕРО-КАВКАЗСКИЙ ФЕДЕРАЛЬНЫЙ ОКРУГ (СКФО) ===
    {
        "id": "CAM_RU_GRV_01",
        "name": "Грозный — МФК Грозный-Сити & Мечеть «Сердце Чечни»",
        "city": "Грозный",
        "city_en": "Grozny",
        "region": "Чеченская Республика",
        "district": "Северо-Кавказский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan / Architecture",
        "lat": 43.3179,
        "lon": 45.6946,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://chechen.camera/grozny_city_heart",
        "snapshot_url": "https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Вайнах Телеком / Безопасный Грозный",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_MCX_01",
        "name": "Махачкала — Набережная Каспийского Моря & Городской Пляж",
        "city": "Махачкала",
        "city_en": "Makhachkala",
        "region": "Республика Дагестан",
        "district": "Северо-Кавказский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Maritime & Caspian",
        "lat": 42.9831,
        "lon": 47.5046,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://dagestan.cam/caspian_beach",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "ДагТелеком / Каспий онлайн",
        "status": "ONLINE",
    },
    {
        "id": "CAM_RU_STW_01",
        "name": "Ставрополь — Площадь Ленина & Крепостная Гора",
        "city": "Ставрополь",
        "city_en": "Stavropol",
        "region": "Ставропольский край",
        "district": "Северо-Кавказский ФО",
        "country": "RU",
        "flag": "🇷🇺",
        "category": "Metropolitan",
        "lat": 45.0445,
        "lon": 41.9708,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://stavropol.cam/krepost_gora",
        "snapshot_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Зеленая Точка Ставрополь",
        "status": "ONLINE",
    },
]

# ----------------------------------------------------------------------
# 2. INTERNATIONAL OPEN CAMERAS DIRECTORY (Global Hubs & Straits)
# ----------------------------------------------------------------------
GLOBAL_CAMERAS_CATALOG: List[Dict[str, Any]] = [
    # --- Maritime Straits & Chokepoints ---
    {
        "id": "CAM_TR_IST_01",
        "name": "Стамбул — Босфорский пролив / Сарайбурну (Черноморский транзит)",
        "city": "Стамбул",
        "city_en": "Istanbul",
        "region": "Marmara",
        "district": "Maritime Chokepoint",
        "country": "TR",
        "flag": "🇹🇷",
        "category": "Maritime & Chokepoints",
        "lat": 41.0151,
        "lon": 28.9795,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://ibbtube.ibb.gov.tr/live/bosphorus",
        "snapshot_url": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "IBB Istanbul / Coastal Safety Directorate",
        "status": "ONLINE",
    },
    {
        "id": "CAM_PA_PTY_01",
        "name": "Панамский Канал — Шлюзы Мирафлорес (Тихоокеанский вход)",
        "city": "Панама",
        "city_en": "Panama City",
        "region": "Panama Canal Zone",
        "district": "Maritime Chokepoint",
        "country": "PA",
        "flag": "🇵🇦",
        "category": "Maritime & Chokepoints",
        "lat": 8.9972,
        "lon": -79.5932,
        "fov_deg": 120,
        "stream_type": "snapshot",
        "stream_url": "https://multimedia.panama-canal.com/webcams/miraflores_locks",
        "snapshot_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 15,
        "operator": "Panama Canal Authority (ACP)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_EG_PSD_01",
        "name": "Суэцкий Канал — Порт-Саид (Средиземноморский вход)",
        "city": "Порт-Саид",
        "city_en": "Port Said",
        "region": "Suez Canal Zone",
        "district": "Maritime Chokepoint",
        "country": "EG",
        "flag": "🇪🇬",
        "category": "Maritime & Chokepoints",
        "lat": 31.2653,
        "lon": 32.3019,
        "fov_deg": 150,
        "stream_type": "snapshot",
        "stream_url": "https://suezcanal.gov.eg/live/port_said_entrance",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 10,
        "operator": "Suez Canal Authority (SCA)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_ES_GIB_01",
        "name": "Гибралтарский Пролив — Тарифа / Мыс Марроки (Вход в Средиземное море)",
        "city": "Тарифа",
        "city_en": "Tarifa",
        "region": "Andalusia",
        "district": "Maritime Chokepoint",
        "country": "ES",
        "flag": "🇪🇸",
        "category": "Maritime & Chokepoints",
        "lat": 36.0024,
        "lon": -5.6083,
        "fov_deg": 220,
        "stream_type": "hls",
        "stream_url": "https://live.skylinewebcams.com/strait_gibraltar_tarifa",
        "snapshot_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "SkylineWebcams Spain",
        "status": "ONLINE",
    },
    {
        "id": "CAM_SG_SIN_01",
        "name": "Сингапурский Пролив — Marina South Pier & Keppel Harbour",
        "city": "Сингапур",
        "city_en": "Singapore",
        "region": "Central Area",
        "district": "Maritime Chokepoint",
        "country": "SG",
        "flag": "🇸🇬",
        "category": "Maritime & Chokepoints",
        "lat": 1.2644,
        "lon": 103.8640,
        "fov_deg": 190,
        "stream_type": "hls",
        "stream_url": "https://mpa.gov.sg/live/singapore_strait_south",
        "snapshot_url": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Maritime and Port Authority of Singapore",
        "status": "ONLINE",
    },
    {
        "id": "CAM_NL_RTM_01",
        "name": "Роттердам — Европорт / Maasvlakte (Крупнейший порт Европы)",
        "city": "Роттердам",
        "city_en": "Rotterdam",
        "region": "South Holland",
        "district": "Maritime Hub",
        "country": "NL",
        "flag": "🇳🇱",
        "category": "Maritime & Port",
        "lat": 51.9566,
        "lon": 4.0450,
        "fov_deg": 200,
        "stream_type": "hls",
        "stream_url": "https://portofrotterdam.com/live/europoort_gate",
        "snapshot_url": "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "Port of Rotterdam Authority",
        "status": "ONLINE",
    },

    # --- World Capitals & Metropolises ---
    {
        "id": "CAM_US_NYC_01",
        "name": "Нью-Йорк — Таймс-Сквер 4K (Манхэттен)",
        "city": "Нью-Йорк",
        "city_en": "New York",
        "region": "New York",
        "district": "North America",
        "country": "US",
        "flag": "🇺🇸",
        "category": "Metropolitan / Traffic",
        "lat": 40.7580,
        "lon": -73.9855,
        "fov_deg": 140,
        "stream_type": "hls",
        "stream_url": "https://earthcam.com/live/timessquare4k",
        "snapshot_url": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "EarthCam USA / NYC DOT",
        "status": "ONLINE",
    },
    {
        "id": "CAM_US_WAS_01",
        "name": "Вашингтон — Капитолий США & Национальная Аллея",
        "city": "Вашингтон",
        "city_en": "Washington D.C.",
        "region": "District of Columbia",
        "district": "North America",
        "country": "US",
        "flag": "🇺🇸",
        "category": "Government & Metropolitan",
        "lat": 38.8899,
        "lon": -77.0090,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://earthcam.com/live/uscapitol",
        "snapshot_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "EarthCam / US Capitol Trust",
        "status": "ONLINE",
    },
    {
        "id": "CAM_JP_TYO_01",
        "name": "Токио — Перекрёсток Сибуя (Shibuya Crossing 4K)",
        "city": "Токио",
        "city_en": "Tokyo",
        "region": "Kanto",
        "district": "East Asia",
        "country": "JP",
        "flag": "🇯🇵",
        "category": "Metropolitan / High-Density",
        "lat": 35.6595,
        "lon": 139.7005,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://shibuya.live/stream/crossing_4k",
        "snapshot_url": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Shibuya Community Cam / NTT Japan",
        "status": "ONLINE",
    },
    {
        "id": "CAM_UK_LON_01",
        "name": "Лондон — Вестминстерский дворец & Биг-Бен",
        "city": "Лондон",
        "city_en": "London",
        "region": "Greater London",
        "district": "Western Europe",
        "country": "UK",
        "flag": "🇬🇧",
        "category": "Government & Metropolitan",
        "lat": 51.4995,
        "lon": -0.1248,
        "fov_deg": 130,
        "stream_type": "hls",
        "stream_url": "https://stream.london.gov.uk/westminster_bridge",
        "snapshot_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "TfL (Transport for London)",
        "status": "ONLINE",
    },
    {
        "id": "CAM_FR_PAR_01",
        "name": "Париж — Эйфелева Башня & Марсово Поле",
        "city": "Париж",
        "city_en": "Paris",
        "region": "Ile-de-France",
        "district": "Western Europe",
        "country": "FR",
        "flag": "🇫🇷",
        "category": "Metropolitan / Landmark",
        "lat": 48.8584,
        "lon": 2.2945,
        "fov_deg": 150,
        "stream_type": "hls",
        "stream_url": "https://paris.camera/eiffel_trocadero",
        "snapshot_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Ville de Paris / SkylineWebcams",
        "status": "ONLINE",
    },
    {
        "id": "CAM_DE_BER_01",
        "name": "Берлин — Бранденбургские Ворота & Парижская Площадь",
        "city": "Берлин",
        "city_en": "Berlin",
        "region": "Berlin",
        "district": "Central Europe",
        "country": "DE",
        "flag": "🇩🇪",
        "category": "Metropolitan / Historic",
        "lat": 52.5163,
        "lon": 13.3777,
        "fov_deg": 120,
        "stream_type": "hls",
        "stream_url": "https://berlin.de/webcams/brandenburg_gate",
        "snapshot_url": "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Land Berlin / Deutsche Telekom",
        "status": "ONLINE",
    },
    {
        "id": "CAM_CN_SHA_01",
        "name": "Шанхай — Набережная Вайтань (The Bund) & Небоскрёбы Пудуна",
        "city": "Шанхай",
        "city_en": "Shanghai",
        "region": "Shanghai",
        "district": "East Asia",
        "country": "CN",
        "flag": "🇨🇳",
        "category": "Metropolitan / Skyline",
        "lat": 31.2397,
        "lon": 121.4900,
        "fov_deg": 170,
        "stream_type": "hls",
        "stream_url": "https://shanghai.gov.cn/live/the_bund_lujiazui",
        "snapshot_url": "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Shanghai Municipal Telecommunications",
        "status": "ONLINE",
    },
    {
        "id": "CAM_AE_DXB_01",
        "name": "Дубай — Бурдж-Халифа & Дубай Молл (Downtown Dubai)",
        "city": "Дубай",
        "city_en": "Dubai",
        "region": "Dubai",
        "district": "Middle East",
        "country": "AE",
        "flag": "🇦🇪",
        "category": "Metropolitan / Architecture",
        "lat": 25.1972,
        "lon": 55.2744,
        "fov_deg": 180,
        "stream_type": "hls",
        "stream_url": "https://dubai.camera/downtown_burjkhalifa",
        "snapshot_url": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Emaar / Dubai Smart City",
        "status": "ONLINE",
    },
    {
        "id": "CAM_AU_SYD_01",
        "name": "Сидней — Сиднейская Опера & Харбор-Бридж (Port Jackson)",
        "city": "Сидней",
        "city_en": "Sydney",
        "region": "New South Wales",
        "district": "Oceania",
        "country": "AU",
        "flag": "🇦🇺",
        "category": "Maritime & Harbor",
        "lat": -33.8568,
        "lon": 151.2153,
        "fov_deg": 200,
        "stream_type": "hls",
        "stream_url": "https://sydney.live/harbour_opera",
        "snapshot_url": "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=900&auto=format&fit=crop&q=80",
        "resolution": "4K UHD",
        "fps": 30,
        "operator": "Sydney Harbour Trust / EarthCam",
        "status": "ONLINE",
    },

    # --- Space, Aviation & Orbital Streams ---
    {
        "id": "CAM_INTL_ISS_01",
        "name": "МКС — Прямая Трансляция Земли HD (NASA / ESA HDEV)",
        "city": "Низкая Околоземная Орбита",
        "city_en": "Low Earth Orbit (420 km)",
        "region": "Space",
        "district": "Orbital",
        "country": "INTL",
        "flag": "🛰️",
        "category": "Aviation & Space",
        "lat": -12.4,
        "lon": -145.2,
        "fov_deg": 360,
        "stream_type": "hls",
        "stream_url": "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
        "snapshot_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "NASA Johnson Space Center / ESA",
        "status": "ONLINE",
    },
    {
        "id": "CAM_US_KSC_01",
        "name": "Мыс Канаверал — Стартовый Комплекс 39A (NASA Kennedy Space Center)",
        "city": "Мыс Канаверал",
        "city_en": "Cape Canaveral",
        "region": "Florida",
        "district": "North America",
        "country": "US",
        "flag": "🇺🇸",
        "category": "Aviation & Space",
        "lat": 28.6083,
        "lon": -80.6042,
        "fov_deg": 140,
        "stream_type": "hls",
        "stream_url": "https://nasa.gov/live/ksc_pad39a",
        "snapshot_url": "https://images.unsplash.com/photo-1517976487507-59a5e18db292?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 30,
        "operator": "NASA / Space Coast Webcams",
        "status": "ONLINE",
    },
    {
        "id": "CAM_DE_FRA_01",
        "name": "Франкфурт — Аэропорт FRA (Взлётно-посадочные полосы 25C/07C)",
        "city": "Франкфурт-на-Майне",
        "city_en": "Frankfurt",
        "region": "Hesse",
        "district": "Central Europe",
        "country": "DE",
        "flag": "🇩🇪",
        "category": "Aviation & Space",
        "lat": 50.0379,
        "lon": 8.5622,
        "fov_deg": 160,
        "stream_type": "hls",
        "stream_url": "https://fraport.de/webcam/runway25",
        "snapshot_url": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&auto=format&fit=crop&q=80",
        "resolution": "1080p FHD",
        "fps": 25,
        "operator": "Fraport AG / Aviation Spotters",
        "status": "ONLINE",
    },
]

# Combined Master Catalog
ALL_CAMERAS: List[Dict[str, Any]] = RU_CAMERAS_CATALOG + GLOBAL_CAMERAS_CATALOG


# ----------------------------------------------------------------------
# 3. HELPER FUNCTIONS & REGIONAL INDEXING
# ----------------------------------------------------------------------
def get_cities_summary() -> List[Dict[str, Any]]:
    """Returns a directory of all covered cities with their camera counts and coordinates."""
    cities_map: Dict[str, Dict[str, Any]] = {}

    for cam in ALL_CAMERAS:
        city = cam["city"]
        if city not in cities_map:
            cities_map[city] = {
                "city": city,
                "city_en": cam.get("city_en", city),
                "region": cam.get("region", ""),
                "district": cam.get("district", ""),
                "country": cam["country"],
                "flag": cam["flag"],
                "lat": cam["lat"],
                "lon": cam["lon"],
                "camera_count": 0,
                "cameras": [],
            }
        cities_map[city]["camera_count"] += 1
        cities_map[city]["cameras"].append(cam["id"])

    return sorted(list(cities_map.values()), key=lambda c: (c["country"] != "RU", -c["camera_count"], c["city"]))


# ----------------------------------------------------------------------
# 4. API ENDPOINTS
# ----------------------------------------------------------------------
@router.get("")
@router.get("/")
async def list_open_cameras(
    search: Optional[str] = Query(None, description="Текстовый поиск по городу, региону или названию"),
    country: Optional[str] = Query(None, description="Код страны (RU, US, TR, etc.)"),
    district: Optional[str] = Query(None, description="Федеральный округ РФ или мировой регион"),
    category: Optional[str] = Query(None, description="Категория (Metropolitan, Maritime, Aviation, etc.)"),
    limit: int = Query(200, ge=1, le=500),
):
    """
    Возвращает каталог открытых публичных камер видеонаблюдения с гибкой фильтрацией.
    Поддерживает поиск по всем городам РФ и мира.
    """
    air_gap = is_air_gap_enabled()
    results = ALL_CAMERAS

    if country:
        c_upper = country.upper()
        results = [c for c in results if c["country"] == c_upper]

    if district:
        d_lower = district.lower()
        results = [c for c in results if d_lower in c.get("district", "").lower()]

    if category:
        cat_lower = category.lower()
        results = [c for c in results if cat_lower in c.get("category", "").lower()]

    if search:
        s_lower = search.lower().strip()
        results = [
            c for c in results
            if s_lower in c["name"].lower()
            or s_lower in c["city"].lower()
            or s_lower in c.get("city_en", "").lower()
            or s_lower in c.get("region", "").lower()
            or s_lower in c.get("operator", "").lower()
        ]

    # In Air-Gapped Stealth Mode, we ensure no live remote stream leakage
    sanitized = []
    for c in results[:limit]:
        item = dict(c)
        if air_gap:
            item["status"] = "AIR_GAPPED_STEALTH"
            item["stream_url"] = "/api/cameras/offline_test_pattern"
            item["snapshot_url"] = "/api/cameras/offline_test_pattern"
        sanitized.append(item)

    return {
        "success": True,
        "air_gap_mode": air_gap,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "total_catalog": len(ALL_CAMERAS),
        "ru_catalog_count": len(RU_CAMERAS_CATALOG),
        "global_catalog_count": len(GLOBAL_CAMERAS_CATALOG),
        "matched_count": len(sanitized),
        "cameras": sanitized,
    }


@router.get("/cities")
async def list_cities():
    """
    Возвращает реестр всех доступных городов РФ и мира с количеством открытых камер.
    Позволяет быстро переключать города на Видеостене (CCTV Matrix).
    """
    cities = get_cities_summary()
    ru_cities = [c for c in cities if c["country"] == "RU"]
    global_cities = [c for c in cities if c["country"] != "RU"]

    return {
        "success": True,
        "total_cities": len(cities),
        "ru_cities_count": len(ru_cities),
        "global_cities_count": len(global_cities),
        "cities": cities,
    }


@router.get("/detail/{camera_id}")
async def get_camera_detail(camera_id: str):
    """
    Возвращает подробные технические параметры конкретной камеры и ссылку на прямой поток.
    """
    cam = next((c for c in ALL_CAMERAS if c["id"] == camera_id), None)
    if not cam:
        raise HTTPException(status_code=404, detail=f"Камера {camera_id} не найдена в каталоге")

    air_gap = is_air_gap_enabled()
    res = dict(cam)
    if air_gap:
        res["status"] = "AIR_GAPPED_STEALTH"
        res["stream_url"] = "/api/cameras/offline_test_pattern"

    return {
        "success": True,
        "air_gap_mode": air_gap,
        "camera": res,
    }


@router.get("/offline_test_pattern")
async def offline_test_pattern():
    """
    Генерирует тактическую испытательную таблицу (SMPTE color bars / HUD grid)
    в режиме Air-Gapped Stealth Mode без выхода в интернет.
    """
    svg_data = """<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360">
      <rect width="640" height="360" fill="#020617"/>
      <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
        <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#1e293b" stroke-width="1"/>
      </pattern>
      <rect width="640" height="360" fill="url(#grid)" />
      <circle cx="320" cy="180" r="80" fill="none" stroke="#0ea5e9" stroke-width="1.5" stroke-dasharray="6,4"/>
      <circle cx="320" cy="180" r="40" fill="none" stroke="#0ea5e9" stroke-width="1"/>
      <line x1="220" y1="180" x2="420" y2="180" stroke="#0ea5e9" stroke-width="1"/>
      <line x1="320" y1="80" x2="320" y2="280" stroke="#0ea5e9" stroke-width="1"/>
      <text x="320" y="175" fill="#38bdf8" font-family="monospace" font-size="12" font-weight="bold" text-anchor="middle">ARGUS AIR-GAP STEALTH MODE</text>
      <text x="320" y="195" fill="#94a3b8" font-family="monospace" font-size="10" text-anchor="middle">EXTERNAL EGRESS SOCKETS BLOCKED</text>
    </svg>"""
    return Response(content=svg_data, media_type="image/svg+xml")
